version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run dev
  test:
    requires:
      - build
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test



# version: 2

# jobs:
#   build:
#     docker:
#       # the Docker image with Cypress dependencies
#       - image: cypress/base:8
#         environment:
#           ## this enables colors in the output
#           TERM: xterm
#     parallelism: 1
#     steps:
#       - checkout
#       - run: npm install
#       - save_cache:
#           key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
#           paths:
#             - ~/.npm
#             - ~/.cache
#       - run: 
#           name: Boot Up App Server 
#           command: npm run dev 
#       - run:
#           name: Running E2E tests with Cypress
#           command: npm test
#       - store_test_results:
#           path: cypress-results

