version: 2
jobs:
  build_and_test:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps
      - run: 
           command: |
            npm install
            npm run dev
            npm test
  deploy:
      - run: echo 'hi!'
        

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build_and_test
      - deploy


          


