version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps
      - run: 
           command: |
            npm install
            npm run dev
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          at: /tmp/workspace
          paths:
            - node_modules
            - cypress
            - cypress.json
            - app

  test:
    docker:
      - image: cypress/base:8
    steps:
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          
          
          


