version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run:
          command: |
            echo Installing dependencies and starting server
            npm install
            npm run dev
  test:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
          
          
          


