version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps
      - run: 
           command: |
           name: Install Dependencies 
            npm install
           name: Start Server
            npm run dev
           name: Run tests 
            npm test


